### ISSUE TITLE
docker errors

### ISSUE THREAD

**Issue by developmentkw** [BarcodeAPI/server#15]
I got two errors for docker, first one is a misspelling:

root@android-linux:~/docker/server# docker build -t barcodeAPIServer . ---> this I copied directly from the github readme 

[+] Building 0.0s (0/0)                                                                                                                                                          docker:default
ERROR: invalid tag "barcodeAPIServer": repository name must be lowercase

--------------------------------------------------------------------------------------------------------
this error I get when I run the docker:
root@android-linux:~/docker/server# docker run -p 9800:8080 -v $(pwd)/config:/config barcodeapiserver

Starting...

java.lang.NullPointerException: inStream parameter is null
        at java.base/java.util.Objects.requireNonNull(Unknown Source)
        at java.base/java.util.Properties.load(Unknown Source)
        at com.mclarkdev.tools.liblog.LibLog.loadStrings(LibLog.java:70)
        at org.barcodeapi.core.ServerLauncher.<init>(ServerLauncher.java:72)
        at org.barcodeapi.Launcher.main(Launcher.java:36)
Exception in thread "main" java.lang.NullPointerException
        at org.barcodeapi.Launcher.invokeSystemShutdown(Launcher.java:67)
        at org.barcodeapi.Launcher.main(Launcher.java:45)
note: when I run via jar command , it works .

**Comment by Kry9toN** [comment]
same issue, what you mean run via jar?

**Comment by MClarkDev** [comment]
Are you trying to boot this on a system that does not have `en_us` set as the default language?
It seems like the server is failing to load the localized strings file, of which only English exists.

https://github.com/BarcodeAPI/server/tree/master/src/main/resources/strings

**Comment by MClarkDev** [comment]
You can also launch the server with an extra argument to for the use of the English language file:

`java -jar server.jar --language en_US`
